package swingFrontEnd;

import infra.Parameters;
import infra.MyDevice;
import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.Timer;
import javax.swing.UIManager;
import jssc.SerialPortList;

/**
 *
 * @author Claudimir Lucio do Lago
 */
public class FrontEnd extends javax.swing.JFrame {

    MyDevice myDevice;
    Parameters par = new Parameters();
    String[] baudRate = {"110", "150", "300", "1200", "2400", "4800", "9600",
        "19200", "38400", "57600", "115200", "230400", "460800", "921600"};

    private void initMyDevice() {
        jComboBox_port.setModel(new javax.swing.DefaultComboBoxModel(SerialPortList.getPortNames()));
        jComboBox_baudRate.setModel(new javax.swing.DefaultComboBoxModel(baudRate));
        jPanel_This_Port.setVisible(false);
        par = Parameters.retrieve("last.dat");
        jComboBox_port.setSelectedItem(par.portaSerial);
        jComboBox_baudRate.setSelectedItem(String.valueOf(par.baudRate));
        myDevice = new MyDevice('m', 's');
        jLabel_status.setText("disconnected   |   not engaded");
    }

    javax.swing.Action updateEach300ms = new javax.swing.AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if (myDevice.isSerialConnected()) {
                String message = myDevice.getLastMessage();
                if (!message.contentEquals("")) {
                    jLabel_from_the_port.setText(message);
                }
                if (myDevice.isEngaged()) {
                }
            }
        }
    };

    public FrontEnd() {
        initComponents();
        /**
         * This is for the Front End generated by NetBeans.
         */
        CleanUpAdapter cleaner = new CleanUpAdapter();
        this.addWindowListener(cleaner);

        jTabbedPane_Geral.setEnabled(false);
        /**
         * Disable everything, but the connection tab
         */

        initMyDevice();

        new Timer(300, updateEach300ms).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser_directory = new javax.swing.JFileChooser();
        PanelStatus = new javax.swing.JPanel();
        jLabel_status = new javax.swing.JLabel();
        jTabbedPane_Geral = new javax.swing.JTabbedPane();
        jPanel_Connection = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_port = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_baudRate = new javax.swing.JComboBox();
        jButton_ConectSerial = new javax.swing.JButton();
        jPanel_This_Port = new javax.swing.JPanel();
        jTextField_command_line = new javax.swing.JTextField();
        jButton_send_a_message = new javax.swing.JButton();
        jLabel_title_from_the_serial = new javax.swing.JLabel();
        jLabel_from_the_port = new javax.swing.JLabel();
        jButton_Accept = new javax.swing.JButton();
        jPanel_Program = new javax.swing.JPanel();

        jFileChooser_directory.setCurrentDirectory(new java.io.File("C:\\lixo"));
        jFileChooser_directory.setDialogTitle("Place to store the experiments");
        jFileChooser_directory.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Demo");
        setResizable(false);

        PanelStatus.setBorder(javax.swing.BorderFactory.createTitledBorder("Status"));

        jLabel_status.setText("<none>");

        javax.swing.GroupLayout PanelStatusLayout = new javax.swing.GroupLayout(PanelStatus);
        PanelStatus.setLayout(PanelStatusLayout);
        PanelStatusLayout.setHorizontalGroup(
            PanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_status)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelStatusLayout.setVerticalGroup(
            PanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelStatusLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel_status))
        );

        jPanel_Connection.setToolTipText("");

        jLabel1.setText("select com port");

        jComboBox_port.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "com1", "com2" }));

        jLabel2.setText("baud rate");

        jComboBox_baudRate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "9600", "115200" }));

        jButton_ConectSerial.setText("Connect");
        jButton_ConectSerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConectSerialActionPerformed(evt);
            }
        });

        jPanel_This_Port.setBorder(javax.swing.BorderFactory.createTitledBorder("This port"));
        jPanel_This_Port.setToolTipText("This port");
        jPanel_This_Port.setPreferredSize(new java.awt.Dimension(600, 160));

        jButton_send_a_message.setText("send the message");
        jButton_send_a_message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_send_a_messageActionPerformed(evt);
            }
        });

        jLabel_title_from_the_serial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_title_from_the_serial.setText("message from the port:");

        jLabel_from_the_port.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_from_the_port.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_from_the_port.setForeground(new java.awt.Color(102, 0, 102));
        jLabel_from_the_port.setText("<none>");

        jButton_Accept.setText("Accept this port");
        jButton_Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AcceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_This_PortLayout = new javax.swing.GroupLayout(jPanel_This_Port);
        jPanel_This_Port.setLayout(jPanel_This_PortLayout);
        jPanel_This_PortLayout.setHorizontalGroup(
            jPanel_This_PortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_This_PortLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_This_PortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_This_PortLayout.createSequentialGroup()
                        .addComponent(jLabel_title_from_the_serial)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_from_the_port)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_This_PortLayout.createSequentialGroup()
                        .addGap(0, 263, Short.MAX_VALUE)
                        .addComponent(jButton_Accept)
                        .addGap(106, 106, 106))
                    .addGroup(jPanel_This_PortLayout.createSequentialGroup()
                        .addComponent(jTextField_command_line)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_send_a_message))))
        );
        jPanel_This_PortLayout.setVerticalGroup(
            jPanel_This_PortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_This_PortLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel_This_PortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_command_line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_send_a_message))
                .addGap(18, 18, 18)
                .addGroup(jPanel_This_PortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_title_from_the_serial)
                    .addComponent(jLabel_from_the_port))
                .addGap(25, 25, 25)
                .addComponent(jButton_Accept)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_ConnectionLayout = new javax.swing.GroupLayout(jPanel_Connection);
        jPanel_Connection.setLayout(jPanel_ConnectionLayout);
        jPanel_ConnectionLayout.setHorizontalGroup(
            jPanel_ConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ConnectionLayout.createSequentialGroup()
                .addGroup(jPanel_ConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ConnectionLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel_ConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel_ConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_ConnectionLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel2))
                            .addGroup(jPanel_ConnectionLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox_baudRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_ConectSerial))))
                    .addGroup(jPanel_ConnectionLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel_This_Port, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        jPanel_ConnectionLayout.setVerticalGroup(
            jPanel_ConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ConnectionLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel_ConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_ConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_baudRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ConectSerial))
                .addGap(30, 30, 30)
                .addComponent(jPanel_This_Port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        jTabbedPane_Geral.addTab("connection", jPanel_Connection);

        javax.swing.GroupLayout jPanel_ProgramLayout = new javax.swing.GroupLayout(jPanel_Program);
        jPanel_Program.setLayout(jPanel_ProgramLayout);
        jPanel_ProgramLayout.setHorizontalGroup(
            jPanel_ProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );
        jPanel_ProgramLayout.setVerticalGroup(
            jPanel_ProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );

        jTabbedPane_Geral.addTab("program", jPanel_Program);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane_Geral)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane_Geral, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ConectSerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConectSerialActionPerformed
        if (myDevice.isSerialConnected()) {
            myDevice.close();
            jButton_ConectSerial.setText("Connect");
            jButton_Accept.setEnabled(true);
            jLabel_from_the_port.setText("");
            jPanel_This_Port.setVisible(false);
            jTabbedPane_Geral.setEnabled(false);
            jLabel_status.setText("disconnected   |   not engaded");
        } else {
            par.portaSerial = jComboBox_port.getSelectedItem().toString();
            par.baudRate = Integer.parseInt(jComboBox_baudRate.getSelectedItem().toString());
            jButton_ConectSerial.setText("Disconnect");
            jPanel_This_Port.setVisible(myDevice.open(par.portaSerial, par.baudRate));
            jLabel_status.setText("connected   |   not engaded");
        }
    }//GEN-LAST:event_jButton_ConectSerialActionPerformed

    private void jButton_AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AcceptActionPerformed
        if (myDevice.isSerialConnected()) {
            jTabbedPane_Geral.setEnabled(true);
            jButton_Accept.setEnabled(false);
            myDevice.engage();
            jLabel_status.setText("connected   |   engaded");
        }
    }//GEN-LAST:event_jButton_AcceptActionPerformed

    private void jButton_send_a_messageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_send_a_messageActionPerformed
        myDevice.send(jTextField_command_line.getText());
    }//GEN-LAST:event_jButton_send_a_messageActionPerformed

    /**
     * This adapter allows a safe ending procedure for the application when the
     * window is closed.
     */
    private class CleanUpAdapter extends WindowAdapter {

        @Override
        public void windowClosing(WindowEvent we) {
            System.out.println("Cleaning and ending the program...");
            par.save("last.dat");
            myDevice.close();
            System.exit(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
                Logger.getLogger(FrontEnd.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(FrontEnd.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> {
            new FrontEnd().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelStatus;
    private javax.swing.JButton jButton_Accept;
    private javax.swing.JButton jButton_ConectSerial;
    private javax.swing.JButton jButton_send_a_message;
    private javax.swing.JComboBox jComboBox_baudRate;
    private javax.swing.JComboBox jComboBox_port;
    private javax.swing.JFileChooser jFileChooser_directory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_from_the_port;
    private javax.swing.JLabel jLabel_status;
    private javax.swing.JLabel jLabel_title_from_the_serial;
    private javax.swing.JPanel jPanel_Connection;
    private javax.swing.JPanel jPanel_Program;
    private javax.swing.JPanel jPanel_This_Port;
    private javax.swing.JTabbedPane jTabbedPane_Geral;
    private javax.swing.JTextField jTextField_command_line;
    // End of variables declaration//GEN-END:variables
}
